### ISSUE TITLE
widget crashs on tapping on task

### ISSUE THREAD

**Issue by wichy2000** [dmfs/tasks#134]
First: I love your apps. It syncs perfectly with my owncloud-server.

At my Nexus 7 (2013 LTE; with lollipop 5.0.2; not rooted) I use your widget. It shows and refreshs all tasks like it should be.
BUT: When I tap at a single task row it crashs. 
Additional info: Tapping at "+" brings me to "create new task", also tapping at the title works fine.
It's reproducible.

Is it only at my device? If you need further informations, I will give it to you.

**Comment by pcfe** [comment]
It is not only your device.
Nearly same behaviour on a Sony Xperia Tablet Z2 with vendor OS (Android 5.0.2 today);
clicking on a specific task will most times, but not all, lead o crash
clicking on + to add task so far always worked
clicking on title bar to open Tasks App so far always worked

**Comment by TobiasRe** [comment]
Could you please provide an error log / stack trace?

**Comment by wichy2000** [comment]
How do I generate this error log? Via google Reports?

**Comment by dmfs** [comment]
got one, probably happens on tablets only.
```
E/AndroidRuntime(18780): Process: org.dmfs.tasks, PID: 18780
E/AndroidRuntime(18780): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dmfs.tasks/org.dmfs.tasks.TaskListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.dmfs.tasks.TaskGroupPagerAdapter.notifyDataSetChanged()' on a null object reference
E/AndroidRuntime(18780): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
E/AndroidRuntime(18780): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
E/AndroidRuntime(18780): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(18780): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
E/AndroidRuntime(18780): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(18780): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(18780): 	at android.app.ActivityThread.main(ActivityThread.java:5223)
E/AndroidRuntime(18780): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18780): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18780): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/AndroidRuntime(18780): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
E/AndroidRuntime(18780): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.dmfs.tasks.TaskGroupPagerAdapter.notifyDataSetChanged()' on a null object reference
E/AndroidRuntime(18780): 	at org.dmfs.tasks.TaskListActivity.resolveIntentAction(TaskListActivity.java:474)
E/AndroidRuntime(18780): 	at org.dmfs.tasks.TaskListActivity.onCreate(TaskListActivity.java:173)
E/AndroidRuntime(18780): 	at android.app.Activity.performCreate(Activity.java:5933)
E/AndroidRuntime(18780): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
E/AndroidRuntime(18780): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
E/AndroidRuntime(18780): 	... 10 more
W/ActivityManager(  556):   Force finishing activity org.dmfs.tasks/.TaskListActivity
```

**Comment by wichy2000** [comment]
Maybe it helps. In meanwhile I updated to Android 5.1.1 with the same problem.
If I can help in any way, so please let me know. I've got a little experience in android development.

**Comment by TobiasRe** [comment]
We fixed the bug with the next update.
